name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images
      - name: Build and push Docker images
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/rock-paper-scissors
          COMMIT_SHA=${{ github.sha }}
          # Build the Docker image
          docker build -t $IMAGE_NAME:$COMMIT_SHA -t $IMAGE_NAME:latest .
          # Push both tags to Docker Hub
          docker push $IMAGE_NAME:$COMMIT_SHA
          docker push $IMAGE_NAME:latest

      # Deploy on EC2 using Docker Compose
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/eks/rock-paper-scissors-ui
            git pull
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d
